---
title: "R Notebook"
output: html_notebook
---

linear models

```{r}

library(tidyverse)
library(dplyr)
library(ggplot2)
library(MASS)

```

```{r}
daily <- read_csv("daily_node_precip.csv")
head(daily)
```

```{r}
# dataframe that has year as a column, and each node as a column, and the frequency of each node as the data
nodes12_freq <- daily %>%
  group_by(year, node) %>%
  dplyr::summarise(node_freq=length(node))

# make wide
nodes12_freq_wide<-pivot_wider(nodes12_freq, names_from=node, values_from=node_freq) 

# change column names so they aren't integers
colnames(nodes12_freq_wide)<-c("year","n1","n2","n3","n4","n5","n6","n7","n8","n9","n10","n11","n12")
# replace na vals with 0
nodes12_freq_wide[is.na(nodes12_freq_wide)]<-0

head(nodes12_freq_wide)
```



```{r}
# read in annual precip and accum file
annual_PA<-read_csv("annual_accum_precip_LD.csv")
head(annual_PA)
```


```{r}
# join annual_PA with node freq df
df_annual <- merge(annual_PA, nodes12_freq_wide)

head(df_annual)
```

```{r}
# subset dataframes into time periods: 1948-2015, 1957-2015, 1979-2015

df_1900 <-df_annual
df_1948 <- df_annual %>% filter(year>1947)
df_1957 <- df_annual %>% filter(year>1956)
df_1979 <- df_annual %>% filter(year>1978)


```



```{r}

# for 1979-2015
# use stepaic to find best model to explain accum_DSS using annual node frequencies
step<-stepAIC(lm(accum_DSS_m ~ year+ n1 + n2 + n3 + n4 + n5 + n6 + n7 + n8 + n9 + n10 + n11 + n12, data=df_1979), direction="both")
step$anova
```

```{r}
# Final Model:
# accum_DSS_m ~ n4 + n5 + n8 + n10 + n12 + n1

fit_1979_accum <- lm(accum_DSS_m ~ n4 + n5 + n8 + n10 + n12 + n1, df_1979)
summary(fit_1979_accum)
```



```{r}
df_1979_predict <- df_1979

# use predict() to add columns that have the predicted value for accum, and the confidence interval

# interval = "condifence" gives the 95% confidence interval around the mean
df_1979_predict$accum_conf <- predict(fit_1979_accum, newdata = df_1979, interval = 'confidence')
# interval = "predition" gives the 95% confidence interval around each point
df_1979_predict$accum_pred <- predict(fit_1979_accum, newdata = df_1979, interval = 'prediction')
df_1979_predict$accum_fit <- predict(fit_1979_accum, newdata = df_1979)


```

```{r}



df_1979_long <- df_1979_predict %>% 
  # only keep year and accum columns
  subset(select=c(year, accum_DSS_m, accum_fit)) %>% 
  # make long format for easier plotting
  pivot_longer(!year, names_to = "model", values_to="accum")

head(df_1979_long)
```

```{r}

plot_1979_f <-
 ggplot(df_1979_long) +
  geom_line(aes(year, accum, color=model)) + 
      scale_color_manual(labels = c("DSS ice core accumulation", "Predicted DSS ice core accum."),
        values=c("red", "black" )) +
 geom_ribbon(data=df_1979_predict, aes(x=year, ymin=accum_pred[,"lwr"], ymax=accum_pred[,"upr"]), alpha=0.1 ) +
  theme_bw() +
#  scale_x_continuous(breaks = seq(1950,2015,10)) +
  xlim(c(1948,2015)) +
# ylim(c(0.25, 1.35)) +
    theme(
    plot.background = element_blank(),
  #  panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    aspect.ratio=7/20,
    axis.text.y=element_text(size=6),
    axis.text.x=element_text(size=6),
    axis.title.y=element_text(size=7),
  axis.title.x=element_blank(),
    legend.title=element_blank(),
  legend.text = element_text(size=6), 
    legend.position = c(0.22, 0.22),
   legend.key.size = unit(0.4, "cm")
    ) +
  labs(x= "Year", y= "Accumulation (m)") +
   annotate(
    "text",
    x = 1948,
    y = 1.25,
    label = bquote("Adjusted"~R^2~" = 0.306, p = 0.0077"),
    color = "black",
    size=2.5,
    hjust = 0,
    vjust = 1
  )

plot_1979_f

```





```{r}
# use stepaic to find best model to explain accum_DSS using annual node frequencies
step<-stepAIC(lm(accum_DSS_m ~ year+ n1 + n2 + n3 + n4 + n5 + n6 + n7 + n8 + n9 + n10 + n11 + n12, data=df_1957), direction="both")
step$anova
```

```{r}
# Final Model:
# accum_DSS_m ~ n1 + n9 + n11

fit_1957_accum <- lm(accum_DSS_m ~ n1 + n9 + n11, df_1957)
summary(fit_1957_accum)
```




```{r}
df_1957_predict <- df_1957

# use predict() to add columns that have the predicted value for accum, and the confidence interval

df_1957_predict$accum_pred <- predict(fit_1957_accum, newdata = df_1957, interval = 'prediction')
df_1957_predict$accum_fit <- predict(fit_1957_accum, newdata = df_1957)


```

```{r}

df_1957_long <- df_1957_predict %>% 
  # only keep year and accum columns
  subset(select=c(year, accum_DSS_m, accum_fit)) %>% 
  # make long format for easier plotting
  pivot_longer(!year, names_to = "model", values_to="accum")

head(df_1957_long)
```

```{r}

plot_1957_f <-
  ggplot(df_1957_long) +
  geom_line(aes(year, accum, color=model)) + 
      scale_color_manual(labels = c("DSS accum", "predicted accum"),
        values=c("red", "black" )) +
 geom_ribbon(data=df_1957_predict, aes(x=year, ymin=accum_pred[,"lwr"], ymax=accum_pred[,"upr"]), alpha=0.1 ) +
  theme_bw() +
#  scale_x_continuous(breaks = seq(1950,2015,10)) +
  xlim(c(1948,2015)) +
# ylim(c(0.25, 1.35)) +
    theme(
    plot.background = element_blank(),
  #  panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    aspect.ratio=7/20,
    axis.text.y=element_text(size=6),
    axis.text.x=element_text(size=6),
    axis.title.y=element_text(size=7),
  axis.title.x=element_blank(),
  legend.position = "none"
    ) +
  labs(x= "Year", y= "Accumulation (m)") +
   annotate(
    "text",
    x = 1948,
    y = 1.25,
    label = bquote("Adjusted"~R^2~" = 0.240, p = 0.0004"),
    color = "black",
    size=2.5,
    hjust = 0,
    vjust = 1
  )

plot_1957_f
```


```{r}
# use stepaic to find best model to explain accum_DSS using annual node frequencies
step<-stepAIC(lm(accum_DSS_m ~ year+ n1 + n2 + n3 + n4 + n5 + n6 + n7 + n8 + n9 + n10 + n11 + n12, data=df_1948), direction="both")
step$anova
```

```{r}
# Final Model:
# accum_DSS_m ~ n1 + n2 + n3 + n4 + n5 + n6 + n7 + n8 + n9 + n10 + 
  #  n11 + n12

fit_1948_accum <- lm(accum_DSS_m ~ n1 + n2 + n3 + n4 + n5 + n6 + n7 + n8 + n9 + n10 + 
    n11 + n12, df_1948)
summary(fit_1948_accum)
```



```{r}
df_1948_predict <- df_1948

# use predict() to add columns that have the predicted value for accum, and the confidence interval

df_1948_predict$accum_pred <- predict(fit_1948_accum, newdata = df_1948, interval = 'prediction')
df_1948_predict$accum_fit <- predict(fit_1948_accum, newdata = df_1948)

```

```{r}

df_1948_long <- df_1948_predict %>% 
  # only keep year and accum columns
  subset(select=c(year, accum_DSS_m, accum_fit)) %>% 
  # make long format for easier plotting
  pivot_longer(!year, names_to = "model", values_to="accum")

head(df_1948_long)
```

```{r}

plot_1948_f <-
  ggplot(df_1948_long) +
  geom_line(aes(year, accum, color=model)) + 
      scale_color_manual(labels = c("DSS accum", "predicted accum"),
        values=c("red", "black" )) +
 geom_ribbon(data=df_1948_predict, aes(x=year, ymin=accum_pred[,"lwr"], ymax=accum_pred[,"upr"]), alpha=0.1 ) +
  theme_bw() +
#  scale_x_continuous(breaks = seq(1950,2015,10)) +
  xlim(c(1948,2015)) +
 # ylim(c(-0.43, 0.54)) +
    theme(
    plot.background = element_blank(),
  #  panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    aspect.ratio=7/20,
    axis.text.y=element_text(size=6),
    axis.text.x=element_text(size=6),
    axis.title.y=element_text(size=7),
  axis.title.x=element_text(size=7),
  legend.position = "none"
    ) +
  labs(x= "Year", y= "Accumulation (m)") +
   annotate(
    "text",
    x = 1948,
    y = 1.25,
    label = bquote("Adjusted"~R^2~" = 0.169, p = 0.029"),
    color = "black",
    size=2.5,
    hjust = 0,
    vjust = 1
  )

plot_1948_f
```
```{r}
plots_f <- plot_grid(plot_1979_f, plot_1957_f, plot_1948_f ,  labels=c("(a)", "(b)", "(c)"), ncol = 1, nrow = 3, align = "hv", axis= "rl", label_size = 10, label_fontface = "plain")
plots_f
```
```{r}
save_plot("linear_model_plots.pdf", plots_f, ncol = 1, base_height=5.4, base_width =4.9)
```





